name: yicbridge_aj_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  intl_utils: ^2.7.0

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  image_picker: ^0.8.5+3
  get_storage: ^2.0.3
  url_launcher: ^6.1.5
  path_provider: ^2.0.11
  device_info_plus: ^4.1.2
  date_format: ^2.0.6
  flutter_easyloading: ^3.0.5
  pull_to_refresh: ^2.0.0
  supercharged: ^2.1.1
  dio: ^4.0.6
  logger: ^1.1.0
  json_annotation: ^4.6.0
  webview_flutter: ^3.0.4
  webview_flutter_web: ^0.1.0+4
  flutter_easyrefresh: ^2.2.2
  package_info_plus: ^1.4.3+1
  install_plugin:
    git:
      url: https://github.com/Zhangxxl/flutter_install_plugin.git
      ref: master
      path: .
  my_plugin:
    path: ./my_plugin

  leancloud_storage: ^0.7.10
  leancloud_official_plugin: ^1.0.1
  extended_image: ^6.2.1
  json_serializable: ^6.3.1
#  permission_handler: ^8.1.4+2
#  badges: ^2.0.1
#  extended_nested_scroll_view: ^3.0.0
#  flutter_screenutil:
#  extended_tabs: ^2.2.0

dependency_overrides:
   json_serializable: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_gen_runner: ^4.3.0

dev_dependency_overrides:


flutter:
  uses-material-design: true
  assets:
    - resources/image/
    - resources/text/
  generate: true

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/
  line_length: 140

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs: []
